language: ruby
rvm:
  - 2.3
cache: bundler
sudo: false

bundler_args: --jobs=3 --retry=3 --without development production

before_script:
  - bundle exec rake db:create db:migrate db:test:prepare

script:
  - bundle exec rails rubocop
  - bundle exec rails test
