language: ruby
rvm:
  - 2.3
cache: bundler
sudo: false

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

script:
  - bundle exec rails test
  - bundle exec rake rubocop
